version: '3.7'

services:

    node:
        image: dsuite/alpine-nodejs:latest
        command: ["node", "app.js"]
        ports:
            - 3000:3000
        volumes:
            - ./app:/app:ro
